name: deploy

on:
  create:
    tags:
      - v*

jobs:
  build-deploy:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.13.1
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

