name: testing

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build-deploy:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.13.1
      - run: npm install
      - run: npm run lint
